name: 🚀 Feature Request
description: Suggest an idea for datype
labels: ['enhancement', 'needs-triage']
assignees:
  - tienedev

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 
        Please provide as much detail as possible about your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like
      placeholder: I'd like to have a function that...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: API Design
      description: How would you like the API to look?
      render: typescript
      placeholder: |
        import { yourFunction } from 'datype';

        const result = yourFunction(input, options);
        // Expected behavior...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions or features you've considered
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
